### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by ArrestX** [henry-richard7/Browser-password-stealer#16]
Traceback (most recent call last):
  File "C:\tools\tools\check_passwd\Browser-password-stealer-master\chromium_based_browsers.py", line 152, in <module>
    data = get_data(browser_path, "Default", master_key, data_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\tools\check_passwd\Browser-password-stealer-master\chromium_based_browsers.py", line 109, in get_data
    shutil.copy(db_file, 'temp_db')
  File "C:\Program Files (x86)\Lib\shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files (x86)\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:

**Comment by AboveAphid0** [comment]
Oh I had that problem too, it just means that the file couldn't be accessed without administrative access. You can just change:
`data = get_data(browser_path, "Default", master_key, data_type)
save_results(browser, data_type_name, data)`
To:
`try:
    data = get_data(browser_path, "Default", master_key, data_type)
    save_results(browser, data_type_name, data)
except:
    print('\t [-] Failed to receive data')`
And that should fix your problem, (I've found that chrome doesn't block this only microsoft edge, though I haven't tested other browsers)
Hope that helps!

**Comment by hahahahacker2009** [comment]
#22 Fixed?
