### ISSUE TITLE
Bug: Cannot decrypt cookie on chrome-beta and chrome-dev

### ISSUE THREAD

**Issue by hahahahacker2009** [henry-richard7/Browser-password-stealer#24]
Adding chrome-beta and its directory to the list
It can decrypt login data, but not cookies.

Getting Stored Details from chrome-beta
         [!] Getting Login data
         [*] Saved in chrome-beta/login_data.txt
        ------

         [!] Getting Credit cards
         [-] No Data Found!
        ------

         [!] Getting Cookies
Traceback (most recent call last):
  File "C:\Users\env\cache\edge\stealer\chromium_based_browsers.py", line 169, in <module>
    data = get_data(browser_path, profile, master_key, data_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\env\cache\edge\stealer\chromium_based_browsers.py", line 131, in get_data
    row[i] = decrypt_password(row[i], key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\env\cache\edge\stealer\chromium_based_browsers.py", line 98, in decrypt_password
    decrypted_pass = decrypted_pass[:-16].decode()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9f in position 0: invalid start byte

**Comment by henry-richard7** [comment]
It tried in my end for chrome beta it's i am able to decrypt cookies.

![Screenshot (2)](https://github.com/user-attachments/assets/ab0f20f6-2ea0-4fc1-9f80-61629d678956)
![Screenshot (3)](https://github.com/user-attachments/assets/195b739b-07c2-4f30-a378-5a2eb23c2594)
